"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Loader2, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
type Application = { email: string; name: string; phone: string; experience: string; motivation: string; dailyCommitment: boolean; awsAccount: boolean; operatingSystem: string; links: string; submittedAt: string; recordType: "APPLICATION" };
export function AdminApplications({ project }: { project: string }) {
  const [items, setItems] = useState<Application[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const r = await fetch("/api/admin/internships", { cache: "no-store" }); const data = await r.json(); if (!r.ok) throw new Error(data.error); setItems((data.applications || []).filter((x: Application) => x.recordType === "APPLICATION")); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load applications."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  return <main className="min-h-screen bg-muted/30 py-8 sm:py-12"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><Link href="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" />Back to {project}</Link><h1 className="mt-5 text-3xl font-semibold tracking-tight sm:text-4xl">Internship applications</h1><p className="mt-2 text-muted-foreground">Review submitted {project} internship applications.</p></div><Button variant="outline" onClick={load} disabled={loading}><RefreshCw className="mr-2 h-4 w-4" />Refresh</Button></div>
  {loading ? <div className="mt-12 flex items-center justify-center rounded-2xl border bg-card p-16 text-muted-foreground"><Loader2 className="mr-2 h-5 w-5 animate-spin" />Loading applications…</div> : error ? <div className="mt-8 rounded-2xl border border-destructive/30 bg-destructive/10 p-5 text-destructive">{error}</div> : items.length === 0 ? <div className="mt-8 rounded-2xl border bg-card p-12 text-center text-muted-foreground">No applications have been submitted yet.</div> : <div className="mt-8 space-y-4">{items.map((a) => <article key={a.email} className="rounded-2xl border bg-card p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-2 border-b pb-4 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-xl font-semibold">{a.name}</h2><a href={`mailto:${a.email}`} className="text-sm text-primary hover:underline">{a.email}</a><p className="mt-1 text-sm text-muted-foreground">{a.phone}</p></div><time className="text-sm text-muted-foreground">{new Date(a.submittedAt).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST</time></div><dl className="mt-5 grid gap-4 sm:grid-cols-3"><Info label="Daily commitment" value={a.dailyCommitment ? "Yes" : "No"} /><Info label="AWS account" value={a.awsAccount ? "Yes" : "No"} /><Info label="Operating system" value={a.operatingSystem} /></dl><Section title={`AWS ${project === "S3Console" ? "S3" : "DynamoDB"} experience`} text={a.experience} /><Section title="Reason for applying" text={a.motivation} /><Section title="Project and social links" text={a.links} /></article>)}</div>}</div></main>;
}
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>; }
function Section({ title, text }: { title: string; text: string }) { return <section className="mt-5"><h3 className="text-sm font-semibold">{title}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{text}</p></section>; }
